### ISSUE TITLE
Conditional binery operator expected

### ISSUE THREAD

**Issue by hampusboas** [sjitech/ApkRename#2]
Conditional binary operator expected on line 48 in apkRename.sh

**Comment by jjqq2013** [comment]
Than you for your report. Seems your bash does not support  ()  semantics which means array. 
What is your bash version?

**Comment by hampusboas** [comment]
ill think 3.1

**Comment by jjqq2013** [comment]
I think you should use bash 3.2+,
I think the problem is inside following statement(line 48), 
if [[ -z "$2" ]] || [[ "$2" =~ ^-+ ]]; then log "option requires an argument for $1"; exit 1; fi

The "$2" =~ ^-+  means second string match regular expression  ^-+  ( starts with one or more hyphens).

It's said from bash 3.2 change regular expression usage with 3.1.

If you can not use bash 3.2+, you can just remove   "|| [[ "$2" =~ ^-+ ]]". Hope you work fine.

**Comment by hampusboas** [comment]
Thanks man its working. But when i upload the apk to google play it says that my apk needs to be zipaligned so ill run zipalign and when i upload it then it says its not signed... but when i upload the apk from the start it works.

**Comment by jjqq2013** [comment]
Good. 
Sorry i did not call zipalign nor sign, you have to call them manually, 
it seems you have tried zipalign but not yet sign, so you can use following command to sign:

jarsigner -keystore "$debugKeyStoreFile" -sigfile CERT -sigalg SHA1withRSA -digestalg SHA1 -storepass $StorePassword -keypass $keyPassword "$apkPath" $KeyStoreAliasName

Please replace $...
